enum ApplicationStage {
    SEND_INITIAL_URL = "SEND_INITIAL_URL",
    REQUEST_ADDITIONAL_INFO = "REQUEST_ADDITIONAL_INFO",
    SEND_ADDITIONAL_INFO = "SEND_ADDITIONAL_INFO",
    REQUEST_DATA_DETAILS = "REQUEST_DATA_DETAILS",
    SEND_DATA_DETAILS = "SEND_DATA_DETAILS",
    COMPLETED = "COMPLETED",
    WAITING = "WAITING",
    ERROR = "ERROR"
}

export default ApplicationStage;
